fix: fixing amount, originalAmount and isThirdPartyPayer
konnectors/alan pull request #280
Opened 2022-01-25 16:15 UTC by KillianCourvoisier

2022-01-25 16:57 UTC, doubleface requested changes

2022-01-25 16:57 UTC, doubleface commented on src/index.js
> +          isThirdPartyPayer: bill.care_acts[0].reimbursed_to_user === 0,
Je sais que c'est moi qui te l'ai dit mais "=== 0" ne va pas marcher. Quand il n'y a pas de remboursement au user, la valeur est à null -> "=== null"

2022-01-28 10:55 UTC, doubleface approved these changes

2022-01-28 10:55 UTC, doubleface commented on src/index.js
> +      bill.groupAmount = Math.round(groupAmount)
toFixed() enleve déjà les chiffres derrière la virgule. Pas besoin de Math.round en plus

2022-01-28 11:00 UTC, KillianCourvoisier commented on src/index.js
> +      bill.groupAmount = Math.round(groupAmount)
Le soucis c'est que ça me le passe en string le toFixed() ... 
Je me suis débrouillé pour que ça reste un number, je change quand même ?

2022-01-28 11:14 UTC, doubleface commented on src/index.js
> +      bill.groupAmount = Math.round(groupAmount)
Dans, ce cas on enlève le toFixed du coup

2022-01-31 10:04 UTC, merged